package encryptedstorage

import (
	"errors"
	"fmt"

	filippoAge "filippo.io/age"
	"github.com/getsops/sops/v3/age"
	"github.com/getsops/sops/v3/keys"
	"github.com/mohammed90/caddy-encrypted-storage/internal/credstore"
	"go.uber.org/zap"

	"github.com/caddyserver/caddy/v2"
)

func init() {
	caddy.RegisterModule(Age{})
}

// Age is a key type to be used with encryption provider. This key
// type uses [age](age-encryption.org) key-pair for encryption/decryption.
// See more: [https://github.com/getsops/sops#encrypting-using-age](https://github.com/getsops/sops#encrypting-using-age)
type Age struct {
	// The public key generated by `age`.
	// Optional when IdentitySource is "keychain" (derived from stored identity).
	Recipient string `json:"recipient,omitempty"`

	// The private keys generated by `age`.
	// Mutually exclusive with IdentitySource.
	Identities []string `json:"identities,omitempty"`

	// IdentitySource specifies where the age identity (private key) is stored.
	// Supported values: "" (default, use Identities field), "keychain" (OS credential store).
	// Mutually exclusive with Identities.
	IdentitySource string `json:"identity_source,omitempty"`

	// TeamID is the Apple Developer Team ID for macOS keychain ACL.
	// Only used when IdentitySource is "keychain" on macOS.
	// Can also be set at build time via ldflags.
	TeamID string `json:"team_id,omitempty"`

	mk     *age.MasterKey
	logger *zap.Logger
}

// Provision implements caddy.Provisioner.
func (a *Age) Provision(ctx caddy.Context) error {
	a.logger = ctx.Logger()

	r, ok := ctx.Value(caddy.ReplacerCtxKey).(*caddy.Replacer)
	if !ok {
		r = caddy.NewReplacer()
	}
	a.Recipient = r.ReplaceKnown(a.Recipient, "")
	a.TeamID = r.ReplaceKnown(a.TeamID, "")

	if a.IdentitySource != "" {
		return a.provisionFromCredentialStore()
	}

	mk, err := age.MasterKeyFromRecipient(a.Recipient)
	if err != nil {
		return err
	}
	if len(a.Identities) > 0 {
		identities := &age.ParsedIdentities{}
		for k, v := range a.Identities {
			a.Identities[k] = r.ReplaceKnown(v, "")
		}
		if err := identities.Import(a.Identities...); err != nil {
			return err
		}
		identities.ApplyToMasterKey(mk)
	}
	a.mk = mk

	return nil
}

// provisionFromCredentialStore handles identity retrieval from the OS credential store.
func (a *Age) provisionFromCredentialStore() error {
	if a.IdentitySource != "keychain" {
		return fmt.Errorf("unsupported identity_source %q; supported values: keychain",
			a.IdentitySource)
	}
	if len(a.Identities) > 0 {
		return fmt.Errorf("identity and identity_source are mutually exclusive; " +
			"use one or the other, not both")
	}
	if a.Recipient != "" {
		return fmt.Errorf("recipient and identity_source are mutually exclusive; " +
			"the recipient is derived from the identity in the credential store")
	}

	store, err := credstore.New(a.TeamID)
	if err != nil {
		return fmt.Errorf("failed to initialize credential store: %w", err)
	}

	identityBytes, account, err := store.GetFirst(credstore.ServiceName)
	if errors.Is(err, credstore.ErrNotFound) {
		return a.bootstrapKeychainIdentity(store)
	}
	if err != nil {
		return fmt.Errorf("failed to search credential store: %w", err)
	}

	a.logger.Info("Using existing age identity from credential store",
		zap.String("account", account))
	return a.applyKeychainIdentity(string(identityBytes))
}

// bootstrapKeychainIdentity generates a new age keypair and stores it in the credential store.
func (a *Age) bootstrapKeychainIdentity(store credstore.Store) error {
	newIdentity, err := filippoAge.GenerateX25519Identity()
	if err != nil {
		return fmt.Errorf("failed to generate age keypair: %w", err)
	}

	recipientStr := newIdentity.Recipient().String()
	identityStr := newIdentity.String()

	if err := store.Set(credstore.ServiceName, recipientStr, []byte(identityStr)); err != nil {
		return fmt.Errorf("failed to store age identity in credential store: %w", err)
	}

	a.logger.Warn("Generated new age keypair and stored identity in OS credential store",
		zap.String("recipient", recipientStr))

	return a.applyKeychainIdentity(identityStr)
}

// applyKeychainIdentity parses an identity string, derives the recipient,
// and sets up the SOPS master key.
func (a *Age) applyKeychainIdentity(identityStr string) error {
	parsedIdentity, err := filippoAge.ParseX25519Identity(identityStr)
	if err != nil {
		return fmt.Errorf("failed to parse age identity from credential store: %w", err)
	}

	a.Recipient = parsedIdentity.Recipient().String()

	mk, err := age.MasterKeyFromRecipient(a.Recipient)
	if err != nil {
		return fmt.Errorf("failed to create master key from recipient: %w", err)
	}

	identities := &age.ParsedIdentities{}
	if err := identities.Import(identityStr); err != nil {
		return fmt.Errorf("failed to import age identity: %w", err)
	}
	identities.ApplyToMasterKey(mk)

	a.mk = mk
	return nil
}

// CaddyModule implements caddy.Module.
func (a Age) CaddyModule() caddy.ModuleInfo {
	return caddy.ModuleInfo{
		ID: "caddy.storage.encrypted.key.age",
		New: func() caddy.Module {
			return new(Age)
		},
	}
}

// ToMasterkey implements Masterkeyer.
func (a *Age) ToMasterkey() keys.MasterKey {
	return a.mk
}

var (
	_ caddy.Module       = (*Age)(nil)
	_ caddy.Provisioner  = (*Age)(nil)
	_ MasterkeyConverter = (*Age)(nil)
)
